file_format: "1"
id: ergoz
name: ErgoZ
type: shield
url: https://github.com/lqlklu/ergoz-keyboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - ergoz_left
  - ergoz_right
